version: '3.1'
services:
  psql:
    image: postgres
    secrets:
      - 'psql_user'
      - 'psql_pass'
    enviornment:
      POSTGRES_PASSWORD_FILE: /run/secrets/psql_pass
      POSTGRES_USER_FILE: /run/secrets/psql_user
secrets:
  psql_user:
    file: ./psql_user.txt
  psql_pass:
    file: ./psql_pass.txt
