version: '3'

services:
  web1:
    build: .
    env_file:
      - '.env'
    ports:
      - '5000:5000'
    volumes:
      - '$PWD:/app'
    networks:
      - net1  

  redis:
    depends_on:
      - 'web1'
    image: redis:alpine
    env_file:
      - '.env'
    ports:
      - '6379:6379'
    volumes:
      - 'vol1:/data'
    networks:
      - net1  

volumes:
  vol1: {}
networks:
  net1: {}
    
   
